module = "icon"

[icons]
bold              = "bold"
italic            = "italic"
underline         = "underline"
align_v_top       = "align-vertical-justify-start"
align_v_center    = "align-vertical-space-around"
align_v_bottom    = "align-vertical-justify-end"
